### ISSUE TITLE
Fix gitmodule URLs

### ISSUE THREAD

**Issue by stah0121** [raven42/dotfiles#5]
Decided to file an issue instead of a PR because I just hacked together these changes for my own setup and thought I'd share a fresh user experience for installing everything

I had to make these changes to get things working

```
diff --git a/.bashrc b/.bashrc
index b8c3b2c..26670e9 100644
--- a/.bashrc
+++ b/.bashrc
@@ -281,7 +281,7 @@ function set_prompt() {
        format_title
 }
 
-if [ $TERM = xterm ]; then
+if [ $TERM = xterm -o $TERM = xterm-256color ]; then
        export PROMPT_COMMAND=set_prompt
 fi
 
diff --git a/.gitmodules b/.gitmodules
index 7f7269f..156f3ad 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -45,7 +45,7 @@
        url = https://github.com/mbbill/undotree.git
 [submodule ".vim/pack/plugins/start/vim-auto-save"]
        path = .vim/pack/plugins/start/vim-auto-save
-       url = git@github.com:907th/vim-auto-save.git
+       url = https://github.com:/907th/vim-auto-save.git
 [submodule ".vim/pack/plugins/start/minimap.vim"]
        path = .vim/pack/plugins/start/minimap.vim
-       url = git@github.com:wfxr/minimap.vim.git
+       url = https://github.com:/wfxr/minimap.vim.git
```

--- I had a fresh debian 10 install where I used the netinst image so it was bare bones in terms of pre-installed packages, but even with the default v8.1 version of VIM things don't work quite right ... so I think it might be helpful to say explicitly in the installation section that installing VIM && universal ctags from source is required (and do this first)
I found some helpful commands in this URL to remove the old VIM and set the default to the freshly built VIM

https://github.com/ycm-core/YouCompleteMe/wiki/Building-Vim-from-source

--- Still trying to get the unicode fonts to work ... I've installed probably 4 or 5 font packages and based on what I've read about the vimrc file and the enabled features it should be working -- I'll add a note here if I find the missing command/font-package

--- To edit python files without error I had to run 'pip3 install flake8' to get things working ... thought I would mention this because the README doesn't mention it, but overall probably not a huge deal

--- Another thing I discovered was the 'apt-get build-deps vim' command which apparently installs all the dependent packages needed to build vim from source ... running that command cleared up a bunch of errors I was seeing doing the install vim from source .. thought this would be another helpful command to add to the README

**Comment by raven42** [comment]
@stah0121 Can you provide a list of the errors you saw with vim 8.1 on debian base install?

Task list for this issue
- [ ] Fix bashrc for PROMPT_COMMAND
- [ ] Git submodules definition - Change to `https://github.com` for URL
- [ ] Update readme for debian install. Include additional requirements for compiling vim
- [ ] Update readme for debian install. Include additional requirements for universal ctags
- [ ] Update readme for flake8 installation. Possibly fix the [devpanel](https://github.com/raven42/devpanel-vim) plugin to auto-detect flake8 and if not found, don't allow the flake8 integration piece to execute.
- [ ] Update readme for recommended linux distribution and setup (including fonts if needed). Currently suspecting CentOS might be preferred distro, debian is more barebones server installation, where CentOS is more of a workstation type installation. Ubuntu might also be considered, but that is more of a desktop installation.

**Comment by stah0121** [comment]
Looks like a complete checklist -- though personally I'll probably stick with debian :P 

Regarding the fonts
* I tried "fc-cache -f" and then reboot
* I then tried to copy the contents of the $HOME/.fonts directory into my new VM, and then did "fc-cache -f" plus reboot

.. and still the fonts don't seem to be working

I will keep messing with the font stuff and let you know if I find out anything

**Comment by stah0121** [comment]
Resolved the font issue!!

The powerline package plus reboot did the trick
https://packages.debian.org/stretch/powerline

Also, my understanding is that these 2 packages are very helpful for font display issues -- my home setup is correctly displaying all .vimrc characters including Timer / Alarm Clock / etc whereas my work setup doesn't display those characters

https://packages.debian.org/buster/ttf-ancient-fonts
https://packages.debian.org/buster/fonts-noto

**Comment by raven42** [comment]
Updated flake8 checks in devpanel-vim plugin via https://github.com/raven42/devpanel-vim/pull/7

**Comment by raven42** [comment]
@stah0121 for the item:

- Git submodules definition - Change to https://github.com for URL

Is there a reason the `git@github.com:<user>/<repo>` syntax didn't work for you? This actually seems to be the preferred method for ssh authentication.

**Comment by stah0121** [comment]
I was using HTTPS auth initially which is why I don't think it worked previously ... but I was reminded that they are deprecating HTTPS auth so I added my SSH key and pulled to the latest without any issues. So I think we're good to go on all fronts ... I also pulled to the latest on my work VDI and am no longer seeing any flake8 or similar errors when opening python files.

Thanks again for setting this stuff up ... its been really useful & interesting to learn about

**Comment by raven42** [comment]
Have updated all submodules to be https so ssh authentication is not required when cloning.
